### ISSUE TITLE
Bazel 0.6 build only works with deprecation flag

### ISSUE THREAD

**Issue by bnewbold** [livegrep/livegrep#117]
Building livegrep with the current stable upstream bazel:
```
bnewbold@bnewbold-dev$ bazel version
Build label: 0.6.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 5 21:54:59 2017 (1507240499)
Build timestamp: 1507240499
Build timestamp as int: 1507240499
```
I get:
```bnewbold@bnewbold-dev$ bazel build //...
ERROR: /1/livegrep/src/proto/BUILD:6:1: Traceback (most recent call last):
        File "/1/livegrep/src/proto/BUILD", line 6
                go_proto_library(name = "go_proto", protos = ["live..."], ...)
        File "/1/tmp/bazel/_bazel_bnewbold/d91485bda7a9c297f0372930fcc1e422/external/org_pubref_rules_protobuf/go/rules.bzl", line 97, in go_proto_library
                go_library(name = name, srcs = (srcs + [(name...")]), <2 more arguments>)
        File "/1/tmp/bazel/_bazel_bnewbold/d91485bda7a9c297f0372930fcc1e422/external/org_pubref_rules_protobuf/go/rules.bzl", line 100, in go_library
                list(set(((deps + proto_deps) + go_pr...)))
        File "/1/tmp/bazel/_bazel_bnewbold/d91485bda7a9c297f0372930fcc1e422/external/org_pubref_rules_protobuf/go/rules.bzl", line 100, in list
                set(((deps + proto_deps) + go_proto_...))
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: /1/livegrep/src/proto/BUILD:12:1: Traceback (most recent call last):
        File "/1/livegrep/src/proto/BUILD", line 12
                cc_proto_library(name = "cc_proto", protos = ["live..."], ...)
        File "/1/tmp/bazel/_bazel_bnewbold/d91485bda7a9c297f0372930fcc1e422/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 87, in cc_proto_library
                native.cc_library(name = name, srcs = (srcs + [(name...")]), <2 more arguments>)
        File "/1/tmp/bazel/_bazel_bnewbold/d91485bda7a9c297f0372930fcc1e422/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 90, in native.cc_library
                list(set(((deps + proto_deps) + compi...)))
        File "/1/tmp/bazel/_bazel_bnewbold/d91485bda7a9c297f0372930fcc1e422/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 90, in list
                set(((deps + proto_deps) + compile_d...))
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: package contains errors: src/proto
ERROR: error loading package 'src/proto': Package 'src/proto' contains errors
INFO: Elapsed time: 0.161s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Passing the `--incompatible_disallow_set_constructor=false` flag to the `bazel` command does work. I don't know enough about bazel to recommend a fix, or if this is just something to be expected.

**Comment by nelhage** [comment]
Looks like I need to update some of my deps. I'll try to chase that yak sometime this week.
