### ISSUE TITLE
Attempting build results in "no such remote ref"

### ISSUE THREAD

**Issue by brandon-rhodes** [livegrep/livegrep#160]
For some reason Bazel's attempt to fetch the pinned revision of `com_github_nelhage_boost` is resulted in an error, even though I think that ref does exist on the remote:
```
$ bazel build //...
ERROR: error loading package '': Encountered error while reading extension file 'boost/boost.bzl': no such package '@com_github_nelhage_boost//': Traceback (most recent call last):
        File "/home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 69
                _clone_or_update(ctx)
        File "/home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external/bazel_tools/tools/build_defs/repo/git.bzl", line 44, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning com_github_nelhage_boost:
+ cd /home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external
+ rm -rf /home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external/com_github_nelhage_boost
+ git clone --depth=1 https://github.com/nelhage/rules_boost /home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external/com_github_nelhage_boost
Cloning into '/home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external/com_github_nelhage_boost'...
+ cd /home/brhodes/.cache/bazel/_bazel_brhodes/7f6357a54daf9c6f2234f2479b3b3fc6/external/com_github_nelhage_boost
+ git reset --hard d6446dc9de6e43b039af07482a9361bdc6da5237
fatal: Could not parse object 'd6446dc9de6e43b039af07482a9361bdc6da5237'.
+ git fetch --depth=1 origin d6446dc9de6e43b039af07482a9361bdc6da5237:d6446dc9de6e43b039af07482a9361bdc6da5237
error: no such remote ref d6446dc9de6e43b039af07482a9361bdc6da5237
```

**Comment by brandon-rhodes** [comment]
The ref still exists in the history of `master` in the https://github.com/nelhage/rules_boost repository, but it's as if GitHub has turned off `uploadpack.allowReachableSHA1InWant` and the fetch can't succeed any more.

**Comment by nelhage** [comment]
Does the build work after a `bazel clean`? 

This also tbqh looks like a bazel bug; When I wrote the Skylark `git_repository` I specifically didn't use shallow clones because of this problem, and it kind of looks like someone thought they were being clever and added in that feature, which doesn't work for precisely this reason.

**Comment by nelhage** [comment]
Are you running into https://github.com/bazelbuild/bazel/issues/4537 ?

**Comment by brandon-rhodes** [comment]
Yes, I think I may be running into that issue + the fact that GitHub doesn't allow the rule's new backup plan —- a fetch of the specific commit — to work because they apparently don't enable `allowReachableSHA1InWant`:

https://stackoverflow.com/a/43136160/85360

**Comment by brandon-rhodes** [comment]
Could you tag `d6446dc9de6e43b039af07482a9361bdc6da5237` in your repository? Once the commit is marked as a ref, GitHub should allow its download by hash. (Alternatively, I could fork the repo and add a tag myself, but of course it would be most convenient to simply keep our build pointed at your copy — but let me know if for some reason adding a ref to yours isn't feasible!)

**Comment by brandon-rhodes** [comment]
Thanks so much for the quick tagging! Yes, if I name the tag in the rule, then it downloads! But now:
```
error: no such remote ref 44b3bdf7d3645cbf0cfd786c5f105d0af4cf49ca
```
for `io_bazel_rules_go`, which we don't control in any case and so can't push tags to. Meanwhile the docs now recommend HTTPS for everything instead of the git rules. I'll look at both as possibilities.

**Comment by brandon-rhodes** [comment]
That one, happily, had a tag I could name. Now trying to figure out how to depend on `ff3b7e7963daa7cb3b42f8936bc11eda4b960926` for `org_pubref_rules_protobuf` which is, alas, more recent (October) than their most recent (September) release.

**Comment by nelhage** [comment]
It looks like the bazel bug is closed; Are you able to upgrade (or downgrade?) bazel and see if that resolves it?
