### ISSUE TITLE
Bazel build breaking

### ISSUE THREAD

**Issue by inthenets** [livegrep/livegrep#241]
OS: Ubuntu 18.04

Added a few flags due to previous build errors, but still cannot get it to build without stopping.

```
$ bazel build //... --incompatible_depset_union=false --incompatible_new_actions_api=false --incompatible_depset_is_not_iterable=false
INFO: Writing tracer profile to '/home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/command.profile.gz'
DEBUG: Rule 'gflags' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1541971260 +0000"
DEBUG: Call stack for the definition of repository 'gflags' which is a git_repository (rule definition at /home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/test/livegrep/WORKSPACE:40:1
INFO: Call stack for the definition of repository 'boost' which is a http_archive (rule definition at /home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/external/com_github_nelhage_rules_boost/boost/boost.bzl:125:9
 - /home/test/livegrep/WORKSPACE:61:1
ERROR: /home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/external/io_bazel_rules_go/BUILD.bazel:62:1: in go_context_data rule @io_bazel_rules_go//:go_context_data: 
Traceback (most recent call last):
	File "/home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/external/io_bazel_rules_go/BUILD.bazel", line 62
		go_context_data(name = 'go_context_data')
	File "/home/test/.cache/bazel/_bazel_user/3cd0cc0f9af118b008933520cc31b07f/external/io_bazel_rules_go/go/private/context.bzl", line 396, in _go_context_data_impl
		cc_common.configure_features(cc_toolchain = cc_toolchain, reque..., ...)
Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped, and the mandatory parameter 'ctx' of cc_common.configure_features is missing. Please add 'ctx' as a named parameter. See https://github.com/bazelbuild/bazel/issues/7793 for details.
ERROR: Analysis of target '//src/proto:go_config_proto' failed; build aborted: Analysis of target '@io_bazel_rules_go//:go_context_data' failed; build aborted
INFO: Elapsed time: 0.552s
INFO: 0 processes.

FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @com_google_protobuf; Cloning 582743bf40c5d3639a70f98f183914a2c0cd0680 of https://github.com/protocolbuffers/protobuf
```

Apologies, but it's not obvious what exactly to add or modify for the Livegrep build from this message:

> Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped, and the mandatory parameter 'ctx' of cc_common.configure_features is missing. Please add 'ctx' as a named parameter. See https://github.com/bazelbuild/bazel/issues/7793 for details.

**Comment by nelhage** [comment]
Bah, looks like we've bitrotted on bazel versions a fair bit. I'm working on this…

**Comment by nelhage** [comment]
Ok! We now test on Bazel 1.1 and I've also verified the build works locally. I'm hopeful 1.0 also works, but I haven't tested. Please feel free to re-open if you still see issues with a new Bazel.
