### ISSUE TITLE
Unable to build livegrep: 'apple_common' value has no field or method 'objc_proto_aspect'

### ISSUE THREAD

**Issue by JaviDiz94** [livegrep/livegrep#304]
Hello everyone!

I've been trying to build livegrep, but I could´nt.

I'm trying to build it in Windows 10.

I tried with different versions of bazel, starting with 5.0.0-pre. I realized that you commented that you were testing on bazel 4.0.0, so I've tried one more time with that version.

I've also installed the Visual Studio Build Tools 2017 (15,9,34) and 2019 (16.10,4). 

With all these dependencies installed, when I do 
`bazel build //...`
it returns the next log:
```
INFO: Repository go_googleapis instantiated at:
  C:/droidfarm/livegrep/WORKSPACE:71:22: in <toplevel>
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/io_bazel_rules_go/go/private/repositories.bzl:242:11: in go_rules_dependencies
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/io_bazel_rules_go/go/private/repositories.bzl:279:18: in _maybe
Repository rule http_archive defined at:
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'go_googleapis' used the following cache hits instead of downloading the corresponding file.
 * Hash 'bba8988a57dc1d259d8e032f3858b52e9708fb863cd378322e703c79582bd064' for https://mirror.bazel.build/github.com/googleapis/googleapis/archive/079e09a64813291f71759d0e1b5f14b0794dc345.zip
If the definition of 'go_googleapis' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'go_googleapis':
   Traceback (most recent call last):
        File "C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                patch(ctx)
        File "C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, column 21, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch @io_bazel_rules_go//third_party:go_googleapis-deletebuild.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-E' '-p1' < C:/users/jdiz/_bazel_jdiz/qw353qq3/external/io_bazel_rules_go/third_party/go_googleapis-deletebuild.patch"): El sistema no puede encontrar el archivo especificado.
 (error: 2)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                patch(ctx)
        File "C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, column 21, in patch
                fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch @io_bazel_rules_go//third_party:go_googleapis-deletebuild.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-E' '-p1' < C:/users/jdiz/_bazel_jdiz/qw353qq3/external/io_bazel_rules_go/third_party/go_googleapis-deletebuild.patch"): El sistema no puede encontrar el archivo especificado.
 (error: 2)
INFO: Repository remote_java_tools_windows instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:208:6: in <toplevel>
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remotejdk11_win instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:114:6: in <toplevel>
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository boost instantiated at:
  C:/droidfarm/livegrep/WORKSPACE:51:11: in <toplevel>
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/com_github_nelhage_rules_boost/boost/boost.bzl:125:21: in boost_deps
Repository rule http_archive defined at:
  C:/users/jdiz/_bazel_jdiz/qw353qq3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: C:/users/jdiz/_bazel_jdiz/qw353qq3/external/org_golang_google_grpc/status/BUILD.bazel:3:11: @org_golang_google_grpc//status:go_default_library depends on @go_googleapis//google/rpc:status_go_proto in repository @go_googleapis which failed to fetch. no such package '@go_googleapis//google/rpc': Error applying patch @io_bazel_rules_go//third_party:go_googleapis-deletebuild.patch:
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("bash" -c "patch '-E' '-p1' < C:/users/jdiz/_bazel_jdiz/qw353qq3/external/io_bazel_rules_go/third_party/go_googleapis-deletebuild.patch"): El sistema no puede encontrar el archivo especificado.
 (error: 2)
ERROR: Analysis of target '//client/test:go_default_library' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.482s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Sorry if I have missed some information, is my first question. So if I can offer you more information to clarify the question, I would do it without problem. Thanks!

**Comment by abdurraheemali** [comment]
I also cannot build livegrep in windows. Will let you know if I find a fix.

**Comment by abdurraheemali** [comment]
Update: using WSL worked
