### ISSUE TITLE
Bazel build throws error

### ISSUE THREAD

**Issue by gita-codaio** [livegrep/livegrep#327]
Hi,

I cloned and built the repo but I keep getting issues;
```
➜  livegrep git:(main)     bazel build //...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_grail_bazel_compdb' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1571147747 -0700"
DEBUG: Repository com_grail_bazel_compdb instantiated at:
  /Users/gita/code/livegrep/WORKSPACE:117:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: /private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/bazel_gazelle/internal/go_repository.bzl:209:18: org_golang_x_net: gazelle: finding module path for import golang.org/x/sys/windows: finding module path for import golang.org/x/sys/windows: package golang.org/x/sys/windows: build constraints exclude all Go files in /private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20220310020820-b874c991c1a5/windows
gazelle: finding module path for import golang.org/x/sys/windows: finding module path for import golang.org/x/sys/windows: package golang.org/x/sys/windows: build constraints exclude all Go files in /private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20220310020820-b874c991c1a5/windows
gazelle: finding module path for import golang.org/x/sys/windows: finding module path for import golang.org/x/sys/windows: package golang.org/x/sys/windows: build constraints exclude all Go files in /private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/bazel_gazelle_go_repository_cache/pkg/mod/golang.org/x/sys@v0.0.0-20220310020820-b874c991c1a5/windows
ERROR: /private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/com_github_grpc_grpc/BUILD:983:16: in @com_grail_bazel_compdb//:aspects.bzl%compilation_database_aspect aspect on cc_library rule @com_github_grpc_grpc//:debug_location: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/com_grail_bazel_compdb/aspects.bzl", line 268, column 42, in _compilation_database_aspect_impl
		compiler_info = _cc_compiler_info(ctx, target, srcs, feature_configuration, cc_toolchain)
	File "/private/var/tmp/_bazel_gita/174251c50cdeb31139097bc4c31efd22/external/com_grail_bazel_compdb/aspects.bzl", line 137, column 73, in _cc_compiler_info
		compiler_options = cc_common.get_memory_inefficient_command_line(
Error in get_memory_inefficient_command_line: Invalid toolchain configuration: Cannot find variable named 'module_name'.
ERROR: Analysis of target '//:compilation_db' failed; build aborted: 
INFO: Elapsed time: 93.662s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (250 packages loaded, 19033 targets configured)
    Fetching @org_golang_x_crypto; fetching 5s
    Fetching @org_golang_x_text; fetching

```
Haven't altered the repo in any way -- any ideas?
Thanks

**Comment by xvandish** [comment]
Hi, 

I think a recent upgrade to Bazel 5 + some deps broke Mac builds - is that what you're on? 

I had the same issue on mac, looked into it for a bit but as a temporary workaround I just commented out the `com_grail_bazel_compdb` parts. Here's the PR on my fork that includes those changes - https://github.com/xvandish/livegrep/pull/13/files. Look at the changes in the `WORKSPACE` and `BUILD` files. Hope that helps for now.

On Linux I didn't have the `com_grail_bazel_compdb` error, which is probably why CI builds are ok.

**Comment by bzz** [comment]
Using `bazel build //... --features=-layering_check` allows compilation on macOS without the modifications.
That's what [gRPC seems to be doing](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/1f1f923a72b1874737daeffb44e04152425162e8/tools/bazel.rc#123).

There is an open issue in bazel-compilation-database, but it came up in a few other places:
 * https://github.com/grailbio/bazel-compilation-database/issues/101
 * https://github.com/bazelbuild/bazel/issues/16243
 * https://github.com/bazelbuild/rules_foreign_cc/pull/631
